id: ID4CD3394
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T09:40:50+00:00'
last_modified: '2022-06-15T18:00:10.856661+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1CZ1982
  title: དྲང་ངེས་ལེགས་བཤད་སྙིང་པོའི་དཀའ་འགྲེལ་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    C429:
      image_group_id: I1CZ2007
      title: Volume 1 of drang nges legs bshad snying po'i dka' 'grel
      total_pages: 94
      order: 1
      base_file: C429.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
